### ISSUE TITLE
Discard calc operations that operate on zero values

### ISSUE THREAD

**Issue by ben-eb** [MoOx/reduce-css-calc#2]
Would it be possible to discard parts of the `calc()` function that operate on zero values? For example:

``` css
div {
    width: calc(100vw / 2 - 6px + 0px);
}
```

Can be:

``` css
div {
    width: calc(100vw / 2 - 6px);
}
```

And:

``` css
div {
    width: calc(500px - 0px);
}
```

Can be:

``` css
div {
    width: 500px;
}
```

It's from this edge case in CSSO:

https://github.com/css/csso/issues/222

**Comment by MoOx** [comment]
`calc(500px - 0px)` is already transformed to `500px`.

You can try here http://cssnext.github.io/cssnext-playground/ since cssnext use postcss-calc which use this package ;)

For the first example, we need to handle math operator priorities (which is not the case for now).
I am open for a PR for this.

Meanwhile, maybe you can do something like:

``` css
div {
    width: calc(100vw / 2 - (6px + 0px));
}
```

which is transformed to

``` css
div {
    width: calc(100vw / 2 - 6px);
}
```
