### ISSUE TITLE
-calc(...) gives calc() result

### ISSUE THREAD

**Issue by MoOx** [MoOx/reduce-css-calc#30]
Input

```css
div {
  margin-left: -calc(2px *2);
}
```

Output

```css
div {
  margin-left: 4px;
}
```

Expected?

```css 
div {
  margin-left: -4px;
}
```

Reproducible on http://cssnext.io/playground/
