### ISSUE TITLE
Negating values broken in 2.X

### ISSUE THREAD

**Issue by alexlafroscia** [MoOx/reduce-css-calc#32]
The following CSS transform used to work in 1.X

```css
/* source */
foo {
  left: calc(-(100px - 10px));
}
```

```css
/* expected */
foo {
  left: -90px;
}
```

However, as of 2.X, this just throws an error.

If you past the `source` example above into http://cssnext.io/playground/, you can see that nothing is produced (which I take to mean it couldn't compile).

**Comment by lkraav** [comment]
Try multiplying with `-1` instead.

**Comment by alexlafroscia** [comment]
Sure, that works and is what I did. But what used to work should continue to work, too.

**Comment by lkraav** [comment]
> Sure, that works and is what I did. But what used to work should continue to work, too.

Yep. But looks like nobody has the time to find and patch the root cause.

**Comment by MoOx** [comment]
Can you take a look at #31 guys?

**Comment by andyjansson** [comment]
>But what used to work should continue to work, too.

It never worked in browsers. The fact that it used to work in the plugin was the result of a bug.

**Comment by Semigradsky** [comment]
@alexlafroscia 
```css
foo {
  left: calc(-(100px - 10px));
}
```
This is incorrect calc expression. Looks like this breaking in major version update is ok.
