### ISSUE TITLE
Standards or not?

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/reduce-css-calc#37]
Now this library reducing correct `calc` expressions.

For some people it would be convenient to write shorter but incorrect `calc` expressions.
For example
```css
div {
  margin-left: -calc(2px *2);
}
```
instead
```css
div {
  margin-left: calc(-1*(2px * 2));
}
```

There are some issues about this: #30, #32 

I think that we should decide: use ONLY the correct syntax or start supporting an informal syntax.
If we choose the second option, we need to agree on what it will be.
