### ISSUE TITLE
Slow resolution time for certain expressions

### ISSUE THREAD

**Issue by shauns** [MoOx/reduce-css-calc#4]
Using postcss-calc wrapper, I've found a case that the library seems to struggle to resolve:

```
font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
```

If there's anything I can do to give more info let me know! The symptom I get is a (very very) long resolution time when the plug-in is on (500s vs 7s for a webpack run)

**Comment by MoOx** [comment]
It seems the issue is not related to this module directly.
You will see here http://cssnext.io/playground/ that this code take no time to compile on any browser. I guess it's something else in your stack...

``` css
a {
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
  font-size: calc(26.140174776426555px + (43.56695796071093 - 26.140174776426555) * ((100vw - 600px) / (1140 - 600)));
}
```
