### ISSUE TITLE
Plugin is removing comments and it shouldn't do it

### ISSUE THREAD

**Issue by sandrina-p** [MoOx/reduce-css-calc#47]
So, I'm having an issue related to comments that are deleted when those are typed inside the property value. 

In my case, I need to use `comments` in order to use some [RTLCSS](rtlcss.com) features.

```scss
.title {
      margin-top: calc(2rem * 2) /*rtl:2rem*/;
}
```

**Expected Output:**
```scss
.title {
      margin-top: 4rem /*rtl:2rem*/;
}
```

**Actual Output:**
```scss
.title {
   margin-top: 4rem;
}
```

Would it be possible to fix that?

Thank you.
