### ISSUE TITLE
unitless zero value bug

### ISSUE THREAD

**Issue by yksht** [MoOx/reduce-css-calc#7]
Hi :)

I'm using postcss and have following expression:

``` css
div {
    width: calc(100% - $width - $margin);
}
```

and I found strange behavior when try to use zero values:

``` css
// $width: 200px;
// $margin: 0; or $margin: 0px; or $margin: 0px;
// output: 
div {
    width: calc(100% - 200px - 0); // this is not valid expression inside 'calc' and browsers don't calculate it
}
```

but these are valid expressions:

``` css
width: calc(100% - 200px - 0px);
width: calc(100% - 200px - 0%);
```

so my question is: Could you fix this? Or this is a normal behavior?
thank you :)
